version: "3"

services:
    boom-hit-miss-target-service:
        image: "glesbygdsit/boom-hit-miss-target-service"
        environment:
            RABGLITMQ: "amqp:glit:glit@boom-rabbitmq"
            MONGODB_URL: "mongodb://boom-mongo:27017"
            PORT: "1338"
        ports:
            - "1338:1338"
        deploy:
            placement:
                constraints:
                    - node.labels.network == routing_mesh

    boom-rabbitmq:
        image: "rabbitmq:3-management"
        hostname: "boom-rabbitmq"
        deploy:
            placement:
                constraints:
                    - node.labels.network == routing_mesh
                    - node.labels.shared_volumes == yes
        environment:
            RABBITMQ_ERLAND_COOKIE: "SWQONISSEWURSTPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "glit"
            RABBITMQ_DEFAULT_PASS: "glit"
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - volume-rabbitmq-db:/var/lib/rabbitmq/
        labels:
            NAME: "boom-rabbitmq"
    boom-mongo:
        image: "mongo"
        hostname: "boom-mongo"
        deploy:
            placement:
                constraints:
                    - node.labels.shared_volumes == yes
        ports:
            - "27017:27017"
        volumes:
            - volume-mongo-db:/data/db

volumes:
    volume-rabbitmq-db:
    volume-mongo-db:
